on:
    push:
        branches:
            - main
            - release/*
jobs:
    my_job:
        name: deploy to staging
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: IPFS Pinata deploy GitHub action
              uses: popovoleksandr/ipfs-pinata-deploy-action@v1.6.3
              with:
                    path: 'IPFS-command.png'
                    pin-name: 'IPFS-command.png'
                    pinata-api-key: ${{ secrets.PINATA_API_KEY }}
                    pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
                    remove-old: false
                    verbose: false
