on:
    push:
        branches:
            - main
            - release/*
jobs:
    my_job:
        name: deploy to staging
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v1
            - name: IPFS Pinata deploy GitHub action
              uses: popovoleksandr/ipfs-pinata-deploy-action@v1.6.3
              with:
                    path: 'IPFS-command.png'
                    pin-name: 'IPFS-command.png'
                    pinata-api-key: "50c78ccc5c4406224de1"
                    pinata-secret-api-key: "9d9e676232a42b60d643e82cad9e636ae3865fb1be826706049d419c6606bfed"
                    remove-old: false
                    verbose: false
